### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Maxpain177** [apollographql/apollo-tooling#1575]
It will be cool to have a docker image including apollo CLI for CI/CD, like a [sentry-cli](https://hub.docker.com/r/getsentry/sentry-cli)

At this moment, we need to use node docker image, and then install git and apollo globally on every pipeline in our GitLab CI/CD:

```yaml
apollo:service_check:
  stage: test runtime
  interruptible: true
  image: node:$NODE_VERSION-alpine
  script:
    - apk add git
    - npm install -g apollo
    - apollo service:check --key $K8S_SECRET_ENGINE_API_KEY --endpoint $(cat environment_url.txt)
  only:
    refs:
      - merge_requests
  needs:
    - review
  dependencies:
    - review
```
